# Generated by Django 4.2.7 on 2023-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restaurant_surplus_food_event_surplus_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_surplus_food',
            name='uploaded_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_surplus_food',
            name='uploaded_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_surplus_food',
            name='uploaded_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurant_surplus_food',
            name='uploaded_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
