# Generated by Django 4.2.7 on 2023-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_surplus_food_uploaded_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_surplus_food',
            name='timeexpire',
            field=models.CharField(default='uuuuu', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant_surplus_food',
            name='uploadedtime',
            field=models.CharField(default='uuuu', max_length=100),
        ),
    ]
