# Generated by Django 4.2.7 on 2023-11-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_restaurant_surplus_food_timeexpire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_surplus_food',
            name='food_type',
        ),
    ]
