# Generated by Django 4.2.7 on 2023-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_event_surplus_food_food_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_surplus_food',
            name='timeexpire',
        ),
        migrations.RemoveField(
            model_name='restaurant_surplus_food',
            name='uploadedtime',
        ),
        migrations.AlterField(
            model_name='event_surplus_food',
            name='time_expire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_surplus_food',
            name='uploaded_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant_surplus_food',
            name='time_expire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant_surplus_food',
            name='uploaded_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
