# Generated by Django 4.2.7 on 2023-11-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_surplus_food_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_surplus_food',
            fields=[
                ('surplus_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('uploaded_on', models.DateField(auto_now_add=True)),
                ('uploaded_time', models.CharField(max_length=100)),
                ('time_expire', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surplus_food_supplier')),
            ],
        ),
    ]
