# Generated by Django 4.2.7 on 2023-11-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_supplier_surplus_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_surplus_food',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='event_surplus_food',
        ),
        migrations.DeleteModel(
            name='restaurant_surplus_food',
        ),
    ]
