# Generated by Django 4.2.7 on 2023-11-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_surplus_food_supplier_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
    ]
