# Generated by Django 4.2.7 on 2023-11-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_surplus_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, default='')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surplus_requests')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('reply', models.TextField(blank=True, default='')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surplus_requests')),
            ],
        ),
    ]
