from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name=''),
    path('login/', views.login, name='login'),
    path('register/<int:uid>', views.register_func, name='register'),
    path('supplier_reg/', views.supplier_reg, name='supplier_reg'),
    path('delivery_agent_reg/<int:uid>', views.delivery_agent_reg, name='delivery_agent_reg'),
    path('admin_home/<int:uid>', views.admin_home, name='admin_home'),
    path('user_home/<int:uid>', views.user_home, name='user_home'),
    path('supplier_home/<int:uid>', views.supplier_home, name='supplier_home'),
    path('delivery_agent_home/<int:uid>', views.delivery_agent_home, name='delivery_agent_home'),
    path('approvesuppliers/<int:uid>', views.approvesuppliers, name='approvesuppliers'),
    path('approve_supplier/<int:uid>/<int:id>', views.approve_supplier, name='approve_supplier'),
    path('reject_supplier/<int:uid>/<int:id>', views.reject_supplier, name='reject_supplier'),
    path('delivery_agent_list/<int:uid>', views.delivery_agent_list, name='delivery_agent_list'),
    path('user_list/<int:uid>', views.user_list, name='user_list'),
    path('supplier_list/<int:uid>', views.supplier_list, name='supplier_list'),
    path('delete_delivery_agent/<int:uid>/<int:id>', views.delete_delivery_agent, name='delete_delivery_agent'),
    path('delete_supplier/<int:uid>/<int:id>', views.delete_supplier, name='delete_supplier'),
    path('delete_user/<int:uid>/<int:id>', views.delete_user, name='delete_user'),
    path('admin_profile/<int:uid>', views.admin_profile, name='admin_profile'),
    path('edit_admin_profile/<int:uid>', views.edit_admin_profile, name='edit_admin_profile'),
    path('user_profile/<int:uid>', views.user_profile, name='user_profile'),
    path('edit_user_profile/<int:uid>', views.edit_user_profile, name='edit_user_profile'),
    path('supplier_profile/<int:uid>', views.supplier_profile, name='supplier_profile'),
    path('edit_supplier_profile/<int:uid>', views.edit_supplier_profile, name='edit_supplier_profile'),
    path('add_supplier_surplus/<int:uid>', views.add_supplier_surplus, name='add_supplier_surplus'),
    path('supplier_surplus_list/<int:uid>', views.supplier_surplus_list, name='supplier_surplus_list'),
    path('delete_supplier_surplus/<int:uid>/<int:id>', views.delete_supplier_surplus, name='delete_supplier_surplus'),
    path('edit_supplier_surplus/<int:uid>/<int:id>', views.edit_supplier_surplus, name='edit_supplier_surplus'),
    path('user_surplus_list/<int:uid>', views.user_surplus_list, name='user_surplus_list'),
    path('user_surplus_request/<int:uid>/<int:id>', views.user_surplus_request, name='user_surplus_request'),
    path('surplus_accepted_users/<int:uid>', views.surplus_accepted_users, name='surplus_accepted_users'),
    path('accepted_surplus_food/<int:uid>', views.accepted_surplus_food, name='accepted_surplus_food'),
    path('delivery_agent_orders/<int:uid>', views.delivery_agent_orders, name='delivery_agent_orders'),
    path('delivery_completed_tasks/<int:uid>', views.delivery_completed_tasks,name='delivery_completed_tasks'),
    path('pickup_order/<int:uid>/<int:id>/', views.pickup_order, name='pickup_order'),
    path('deliver_order/<int:uid>/<int:id>/', views.deliver_order, name='deliver_order'),
    path('create_complaint/<int:uid>/<int:id>', views.create_complaint, name='create_complaint'),
    path('give_reply/<int:uid>/<int:id>', views.give_reply, name='give_reply'),
    path('complaints_list/<int:uid>', views.complaints_list, name='complaints_list'),
    path('view_complaints_list/<int:uid>', views.view_complaints_list, name='view_complaints_list'),
    path('give_feedback/<int:uid>/<int:id>', views.give_feedback, name='give_feedback'),
    path('give_feedback_reply/<int:uid>/<int:id>', views.give_feedback_reply, name='give_feedback_reply'),
    path('feedback_list/<int:uid>', views.feedback_list, name='feedback_list'),
    path('admin_view_feedback_list/<int:uid>', views.admin_view_feedback_list, name='admin_view_feedback_list'),
    path('view_feedback_list/<int:uid>', views.view_feedback_list, name='view_feedback_list'),
    path('surplus_food_information/<int:uid>', views.surplus_food_information, name='surplus_food_information'),
    path('all_surplus_food_information/<int:uid>', views.all_surplus_food_information, name='all_surplus_food_information'),
    path('all_surplus_information/<int:uid>', views.all_surplus_information, name='all_surplus_information'),
    path('logout/', views.logout, name='logout'),

    # path('customer_list/<int:uid>', views.customer_list, name='customer_list'),
    # path('delivery_agent_list/<int:uid>', views.delivery_agent_list, name='delivery_agent_list'),
    # path('delete_manufacturer/<int:uid>/<int:id>', views.delete_manufacturer, name='delete_manufacturer'),
    # path('tailor_profile/<int:uid>', views.tailor_profile, name='tailor_profile'),
    # path('edit_tailor_profile/<int:uid>', views.edit_tailor_profile, name='edit_tailor_profile'),
    # path('category_list/<int:uid>', views.category_list, name='category_list'),
    # path('add_category/<int:uid>', views.add_category, name='add_category'),
    # path('delete_category/<int:uid>/<int:id>', views.delete_category, name='delete_category'),
    # path('edit_category/<int:uid>/<int:id>', views.edit_category, name='edit_category'),
    # path('designs_list/<int:uid>', views.designs_list, name='designs_list'),
    # path('add_design/<int:uid>', views.add_design, name='add_design'),
    # path('edit_design/<int:uid>/<int:id>', views.edit_design, name='edit_design'),
    # path('delete_design/<int:uid>/<int:id>', views.delete_design, name='delete_design'),
    # path('admin_designs_list/<int:uid>', views.admin_designs_list, name='admin_designs_list'),
    # path('admin_delete_design/<int:uid>/<int:id>', views.admin_delete_design, name='admin_delete_design'),
    # path('materials_list/<int:uid>', views.materials_list, name='materials_list'),
    # path('add_material/<int:uid>', views.add_material, name='add_material'),
    # path('edit_material/<int:uid>/<int:id>', views.edit_material, name='edit_material'),
    # path('delete_material/<int:uid>/<int:id>', views.delete_material, name='delete_material'),
    # path('admin_materials_list/<int:uid>', views.admin_materials_list, name='admin_materials_list'),
    # path('admin_delete_material/<int:uid>/<int:id>', views.admin_delete_material, name='admin_delete_material'),
    # path('get_designs/<int:uid>/<int:id>', views.get_designs, name='get_designs'),
    # path('design_more_details/<int:uid>/<int:id>', views.design_more_details, name='design_more_details'),
    # path('request_tailor/<int:uid>/<int:id>', views.request_tailor, name='request_tailor'),
    # path('view_sew_requests/<int:uid>', views.view_sew_requests, name='view_sew_requests'),
    # path('accept_request/<int:uid>/<int:id>', views.accept_request, name='accept_request'),
    # path('reject_request/<int:uid>/<int:id>', views.reject_request, name='reject_request'),
    # path('track_request/<int:uid>/<int:id>', views.track_request, name='track_request'),
    # path('customer_track_request/<int:uid>/<int:id>', views.customer_track_request, name='customer_track_request'),
    # path('customer_request_history/<int:uid>', views.customer_request_history, name='customer_request_history'),
    # path('cancel_request/<int:uid>/<int:id>', views.cancel_request, name='cancel_request'),
    # path('customer_orders/<int:uid>', views.customer_orders, name='customer_orders'),
    # path('give_measurement/<int:uid>/<int:id>', views.give_measurement, name='give_measurement'),
    # path('tailor_order_list/<int:uid>', views.tailor_order_list, name='tailor_order_list'),
    # path('give_rate_details/<int:uid>/<int:id>', views.give_rate_details, name='give_rate_details'),
    # path('accept_order_rate/<int:uid>/<int:id>', views.accept_order_rate, name='accept_order_rate'),
    # path('reject_order_rate/<int:uid>/<int:id>', views.reject_order_rate, name='reject_order_rate'),
    # path('sewing_rate_details/<int:uid>/<int:id>', views.sewing_rate_details, name='sewing_rate_details'),
    # path('order_placed/<int:uid>', views.order_placed, name='order_placed'),
    # path('my_orders/<int:uid>', views.my_orders, name='my_orders'),
    # path('customer_order_history/<int:uid>', views.customer_order_history, name='customer_order_history'),
    # path('tailor_orders/<int:uid>', views.tailor_orders, name='tailor_orders'),
    # path('tailor_order_details/<int:uid>/<int:id>', views.tailor_order_details, name='tailor_order_details'),
    # path('tailor_order_history/<int:uid>', views.tailor_order_history, name='tailor_order_history'),
    # path('material_requests/<int:uid>/<int:sewing_id>/<int:material_id>', views.material_requests,
    #      name='material_requests'),
    # path('fabric_request/<int:uid>', views.fabric_request, name='fabric_request'),
    # path('material_requests_list/<int:uid>', views.material_requests_list, name='material_requests_list'),
    # path('material_requests_history/<int:uid>', views.material_requests_history, name='material_requests_history'),
    # path('accept_material_request/<int:uid>/<int:id>/<int:order_id>', views.accept_material_request,
    #      name='accept_material_request'),
    # path('update_tailor_status/<int:uid>/<int:id>', views.update_tailor_status, name='update_tailor_status'),
    # path('delivery_agent_orders/<int:uid>', views.delivery_agent_orders, name='delivery_agent_orders'),
    # path('delivery_agent_order_history/<int:uid>', views.delivery_agent_order_history,
    #      name='delivery_agent_order_history'),
    # path('pickup_order/<int:uid>/<int:id>/', views.pickup_order, name='pickup_order'),
    # path('deliver_order/<int:uid>/<int:id>/', views.deliver_order, name='deliver_order'),
    #
    # path('get_categories/', views.get_categories, name='get_categories'),


]